import car1 from "./Cars/1.jpeg";
import car2 from "./Cars/2.webp";
import car3 from "./Cars/3.jpeg";
import car4 from "./Cars/4.jpg";
import car5 from "./Cars/5.jpg";
import car6 from "./Cars/6.jpg";
import car7 from "./Cars/7.jpeg";
import car8 from "./Cars/8.jpeg";
import car9 from "./Cars/9.webp";
import car10 from "./Cars/10.jpg";
import car11 from "./Cars/11.jpg";
import car12 from "./Cars/12.jpeg";
import car13 from "./Cars/13.jpg";
import car14 from "./Cars/14.jpg";
import car15 from "./Cars/15.jpg";

const Data = [
  {
    id: 1,
    carUrl: car1,
    model: "BMW 5 series",
    people: 4,
    year: 2021,
    speed: "170km/h",
    type: "Gasoline",
    price: "ksh40k",
    liked: false,
    gear: "Automatic",
  },
  {
    id: 2,
    carUrl: car2,
    model: "Lamborghini Urus",
    people: 4,
    year: 2021,
    speed: "180km/h",
    type: "Gasoline",
    price: "ksh70k",
    liked: false,
    gear: "Automatic",
  },
  {
    id: 3,
    carUrl: car3,
    model: "Mercides-Benz A 35 AMG",
    people: 4,
    year: 2022,
    speed: "160km/h",
    type: "Gasoline",
    price: "ksh50k",
    liked: false,
    gear: "Automatic",
  },
  {
    id: 4,
    carUrl: car4,
    model: "Hyandai N",
    people: 4,
    year: 2021,
    speed: "150km/h",
    type: "Hybrid",
    price: "ksh50k",
    liked: false,
    gear: "Automatic",
  },
  {
    id: 5,
    carUrl: car5,
    model: "Tesla ModelX",
    people: 4,
    year: 2022,
    speed: "170km/h",
    type: "Electric",
    price: "ksh65k",
    liked: false,
    gear: "Automatic",
  },
  {
    id: 6,
    carUrl: car6,
    model: "Rolls-Royce Phantom",
    people: 6,
    year: 2021,
    speed: "140km/h",
    type: "Gasoline",
    price: "ksh100k",
    liked: false,
    gear: "Automatic",
  },
  {
    id: 7,
    carUrl: car7,
    model: "Proton X-70",
    people: 4,
    year: 2019,
    speed: "140km/h",
    type: "Gasoline",
    price: "ksh35k",
    liked: false,
    gear: "Automatic",
  },
  {
    id: 8,
    carUrl: car8,
    model: "2023 Ford-Mustang",
    people: 4,
    year: 2023,
    speed: "190km/h",
    type: "Gasoline",
    price: "ksh65k",
    liked: false,
    gear: "Automatic",
  },
  {
    id: 9,
    carUrl: car9,
    model: "Lexus IS ",
    people: 4,
    year: 2023,
    speed: "140km/h",
    type: "Hybrid",
    price: "ksh60k",
    liked: false,
    gear: "Automatic",
  },
  {
    id: 10,
    carUrl: car10,
    model: "BMW M5",
    people: 4,
    year: 2022,
    speed: "175km/h",
    type: "Gasoline",
    price: "ksh55k",
    liked: false,
    gear: "Automatic",
  },
  {
    id: 11,
    carUrl: car11,
    model: "BMW XM SUV",
    people: 4,
    year: 2023,
    speed: "165km/h",
    type: "Hybrid",
    price: "ksh90k",
    liked: false,
    gear: "Automatic",
  },
  {
    id: 12,
    carUrl: car12,
    model: "Toyota Sequoia SUV",
    people: 6,
    year: 2022,
    speed: "170km/h",
    type: "Gasoline",
    price: "ksh55k",
    liked: false,
    gear: "Automatic",
  },
  {
    id: 13,
    carUrl: car13,
    model: "Ford Equator",
    people: 6,
    year: 2023,
    speed: "140km/h",
    type: "Hybrid",
    price: "ksh60k",
    liked: false,
    gear: "Automatic",
  },
  {
    id: 14,
    carUrl: car14,
    model: "Audi S5 Coupe",
    people: 4,
    year: 2021,
    speed: "140km/h",
    type: "Gasoline",
    price: "ksh42k",
    liked: false,
    gear: "Automatic",
  },
  {
    id: 15,
    carUrl: car15,
    model: "Mercides G63 AMG",
    people: 4,
    year: 2023,
    speed: "160km/h",
    type: "Gasoline",
    price: "ksh150k",
    liked: false,
    gear: "Automatic",
  },
];
export default Data;
